### ISSUE TITLE
WP API key config warning message inaccurate

### ISSUE THREAD

**Issue by KevinMZiegler** [iMoneza/wordpress-imoneza#15]
I updated the site http://imoneza-dev-sandbox.cloudapp.net/coffee-magazine to iMoneza Pro, and the process walked me through adding the API Keys.  As I wasn't really paying attention (typical) to the wording, I entered the wrong Resource Management API Key (I entered the Resource Access API Key), and I did enter the proper Resource Management API Secret key.  The message that I was given didn't properly reflect my mistake - see screenshot:
![image](https://cloud.githubusercontent.com/assets/17073742/14328495/8898b468-fbfc-11e5-8d60-9de1b5f151ea.png)

**Comment by aaronsaray** [comment]
Well the API is returning an authentication error - not a not-found when using the wrong API key.  I think this is because somewhere deep down in the code, API keys probably share the same base - so while the API key was wrong, it was actually 'right' too - and found.  So I changed the error message to refer to the fact that the KEY and Secret don't match and to verify them.  Will reassign when this is in QA.
